# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 19 Jun 2017 07:18:32 +0000
*               @ALL          1
*               @user         8
