<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Wed, 02 May 2018 17:43:51 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
